CREATE TABLE posts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title TEXT NOT NULL,
                       content TEXT NOT NULL,

                       CONSTRAINT posts_title_not_blank
                           CHECK (btrim(title) <> ''),

                       CONSTRAINT posts_content_not_blank
                           CHECK (btrim(content) <> '')
);