CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          content TEXT NOT NULL,
                          post_id BIGINT NOT NULL,

                          CONSTRAINT comments_content_not_blank
                              CHECK (btrim(content) <> ''),

                          CONSTRAINT fk_comments_post
                              FOREIGN KEY (post_id)
                                  REFERENCES posts(id)
                                  ON DELETE CASCADE
);